# Generated by Django 5.0 on 2024-02-12 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
                ('maincategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
    ]
