# Generated by Django 5.0 on 2024-02-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=70)),
                ('productdescription', models.CharField(default='', max_length=500)),
                ('icon', models.ImageField(upload_to='static/')),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.brand')),
                ('maincategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.subcategory')),
            ],
        ),
    ]
