# Generated by Django 5.0 on 2024-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerdescription', models.CharField(default='', max_length=500)),
                ('pictures', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
