# Generated by Django 5.0 on 2024-02-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0005_alter_productdetail_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='pictures',
            new_name='icon',
        ),
    ]
