# Generated by Django 5.0 on 2024-05-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0008_banners_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('mobileno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('dob', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('postcode', models.CharField(default='', max_length=70)),
                ('mobileno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.users')),
            ],
        ),
    ]
